# Generated by Django 5.1.4 on 2026-06-20 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_affiliatelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(default=False)),
                ('is_elderly', models.BooleanField(default=False)),
                ('sports_fan', models.BooleanField(default=False)),
                ('music_taste', models.CharField(blank=True, max_length=100)),
                ('other_interests', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pesquisa de interesse',
                'verbose_name_plural': 'pesquisas de interesses',
            },
        ),
    ]
