# Generated by Django 5.1.4 on 2026-06-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
