# Generated by Django 5.1.4 on 2026-06-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_cpf_cnpj_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person_type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
    ]
