# Generated by Django 5.1.4 on 2026-06-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='reference_point',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
