# Generated by Django 5.1.4 on 2026-06-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_address_observation_address_reference_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='is_elderly',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='music_taste',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='sports_fan',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='preferred_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
