# Generated by Django 5.1.4 on 2026-06-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_usersurvey_is_elderly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='primary_intent',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
