# Generated by Django 5.1.4 on 2026-06-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
