# Generated by Django 5.1.4 on 2026-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='destination_cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_shipping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
