# Generated by Django 5.1.4 on 2026-06-19 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('remorse', 'Arrependimento (7 dias)'), ('defect', 'Produto com defeito'), ('wrong', 'Produto errado'), ('late', 'Atraso extremo na entrega')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('approved', 'Aprovado (Aguardando Envio)'), ('shipped_back', 'Em Devolução (Correios)'), ('refunded', 'Estornado'), ('rejected', 'Rejeitado')], default='requested', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('seller_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'solicitação de devolução',
                'verbose_name_plural': 'solicitações de devolução',
            },
        ),
    ]
