# Generated by Django 5.1.4 on 2026-06-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon_current_uses_coupon_is_first_purchase_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='invoice_link',
            field=models.URLField(blank=True, help_text='Link para a Nota Fiscal (PDF)', max_length=500),
        ),
    ]
