# Generated by Django 5.1.4 on 2026-06-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_suborder_invoice_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='carrier_name',
            field=models.CharField(blank=True, help_text='Ex: Correios, Jadlog, Lalamove', max_length=50),
        ),
        migrations.AddField(
            model_name='suborder',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
