# Generated by Django 5.1.4 on 2026-06-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_suborder_carrier_name_suborder_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
