# Generated by Django 5.1.4 on 2026-06-19 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='category',
            name='category_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Em Análise'), ('approved', 'Publicado'), ('banned', 'Banido - Ilícito')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'verbose_name': 'especificação técnica',
                'verbose_name_plural': 'especificações técnicas',
                'unique_together': {('product', 'attribute_name')},
            },
        ),
    ]
