# Generated by Django 5.1.4 on 2026-06-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_promo_ends_at_product_promo_starts_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
