# Generated by Django 5.1.4 on 2026-06-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_clicks_count_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_free_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
