# Generated by Django 5.1.4 on 2026-06-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_estimated_delivery_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura em CM', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento em CM', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso em KG. Ex: 1.500 = 1.5kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largura em CM', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura em CM', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento em CM', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso em KG. Ex: 1.500 = 1.5kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largura em CM', max_digits=6, null=True),
        ),
    ]
