# Generated by Django 5.1.4 on 2026-06-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_height_product_length_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL externa para imagens (usado caso S3 não esteja ativo)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
