# Generated by Django 5.1.4 on 2026-06-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_boosted',
            field=models.BooleanField(default=False, help_text='Produto impulsionado no catálogo'),
        ),
    ]
