# Generated by Django 5.1.4 on 2026-06-19 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sellers/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='sellers/banners/')),
                ('commission_rate', models.DecimalField(decimal_places=4, default='0.0300', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Aguardando aprovação'), ('approved', 'Aprovado'), ('suspended', 'Suspenso'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('mp_access_token', models.CharField(blank=True, max_length=512)),
                ('mp_refresh_token', models.CharField(blank=True, max_length=512)),
                ('mp_user_id', models.CharField(blank=True, max_length=50)),
                ('mp_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pix_key', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
                'ordering': ['-created_at'],
            },
        ),
    ]
