# Generated by Django 5.1.4 on 2026-06-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='mp_access_token',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='mp_refresh_token',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='mp_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='mp_user_id',
        ),
        migrations.AddField(
            model_name='seller',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
