# Generated by Django 5.1.4 on 2026-06-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_remove_seller_mp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='strike_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de infrações graves (produtos ilícitos).'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default='0.1500', max_digits=5),
        ),
    ]
