# Generated by Django 5.1.4 on 2026-06-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='banner2',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/banners/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='banner3',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/banners/'),
        ),
    ]
