# Generated by Django 5.1.4 on 2026-06-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_seller_banner2_seller_banner3'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='max_installments',
            field=models.PositiveIntegerField(default=12, help_text='Número máximo de parcelas permitidas para os produtos desta loja.'),
        ),
    ]
