# Generated by Django 5.1.4 on 2026-06-21 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon_current_uses_coupon_is_first_purchase_only_and_more'),
        ('sellers', '0007_seller_max_installments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_buyer_reviews', to='sellers.seller')),
                ('sub_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_review', to='orders.suborder')),
            ],
            options={
                'verbose_name': 'avaliação do comprador',
                'verbose_name_plural': 'avaliações dos compradores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_seller_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='sellers.seller')),
                ('sub_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_review', to='orders.suborder')),
            ],
            options={
                'verbose_name': 'avaliação do lojista',
                'verbose_name_plural': 'avaliações dos lojistas',
                'ordering': ['-created_at'],
            },
        ),
    ]
