# Generated by Django 5.1.4 on 2026-06-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_buyerreview_sellerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='banner2_external',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='banner3_external',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='banner_external',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='logo_external',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
