# Generated by Django 5.1.4 on 2026-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_seller_cpf_cnpj_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='stripe_onboarding_complete',
        ),
        migrations.AddField(
            model_name='seller',
            name='efi_payee_code',
            field=models.CharField(blank=True, help_text='Identificador de conta Efí para repasse (Split)', max_length=100),
        ),
    ]
