# Generated by Django 5.1.4 on 2026-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_remove_seller_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Número da conta com o dígito', max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança')], max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_agency',
            field=models.CharField(blank=True, help_text='Agência sem o dígito', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Código do Banco (ex: 341 para Itaú)', max_length=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='main_category',
            field=models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('moda', 'Moda (Geral)'), ('roupas', 'Roupas'), ('calcados', 'Calçados'), ('bolsas', 'Bolsas e Acessórios'), ('moda_fit', 'Moda Fit'), ('moda_esportiva', 'Moda Esportiva'), ('casa', 'Artigos para Casa'), ('ferramentas', 'Ferramentas'), ('alimentos', 'Alimentos'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
