# Generated by Django 5.1.4 on 2026-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_seller_bank_account_seller_bank_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='bank_account_type',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='bank_agency',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='bank_code',
        ),
        migrations.AlterField(
            model_name='seller',
            name='efi_payee_code',
            field=models.CharField(blank=True, help_text='Identificador de Conta Digital Efí para repasse (Split)', max_length=100),
        ),
    ]
