# Generated by Django 5.1.4 on 2026-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0013_remove_seller_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='origin_cep',
            field=models.CharField(blank=True, help_text='CEP de origem do Galpão/Loja para cálculo de frete (Ex: 01001000)', max_length=9),
        ),
    ]
