# Generated by Django 5.1.4 on 2026-06-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0014_seller_origin_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default='0.1200', max_digits=5),
        ),
    ]
