# Generated by Django 5.1.4 on 2026-06-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0016_commission_rate_15_to_12'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_hours',
            field=models.CharField(blank=True, help_text='Horário de funcionamento (ex: Seg a Sex, 08:00 as 18:00)', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='physical_address',
            field=models.TextField(blank=True, help_text='Endereço da loja física ou galpão de distribuição'),
        ),
        migrations.AddField(
            model_name='seller',
            name='primary_color',
            field=models.CharField(default='#E6B53C', help_text='Cor principal da loja (Hexadecimal)', max_length=7),
        ),
        migrations.AddField(
            model_name='seller',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link para vídeo de apresentação (YouTube, Vimeo, etc)', max_length=500, null=True),
        ),
    ]
