# Generated by Django 5.1.4 on 2026-06-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0017_seller_business_hours_seller_physical_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='presentation_video',
            field=models.FileField(blank=True, help_text='Vídeo de apresentação enviado pelo lojista (até 30 MB)', null=True, upload_to='sellers/videos/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link para vídeo de apresentação (YouTube, Vimeo, etc) - legado', max_length=500, null=True),
        ),
    ]
