# Generated by Django 5.1.4 on 2026-06-20 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('funnel_type', models.CharField(choices=[('comprador', 'Comprador (B2C)'), ('lojista', 'Lojista (B2B)'), ('white_label', 'Investidor (White-Label)')], max_length=50)),
                ('source', models.CharField(default='Organic', max_length=100)),
                ('status', models.CharField(choices=[('novo', 'Novo Lead'), ('em_contato', 'Em Contato'), ('negociando', 'Em Negociação'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
