# Generated by Django 5.1.4 on 2026-06-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='sellers.seller'),
        ),
        migrations.AddField(
            model_name='payout',
            name='sub_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='orders.suborder'),
        ),
    ]
