# Generated by Django 5.1.4 on 2026-06-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_refunded_amount_payment_refunded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='mp_payment_id',
            new_name='efi_charge_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_refund_id',
            new_name='efi_refund_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='efi_txid',
        ),
    ]
